# vim:ts=2:sw=2:et
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer global require "phpunit/phpunit=4.8.*"

script:
  - cd test && wget -q -O /tmp/run_unit_tests https://raw.github.com/atk14/Atk14/master/src/scripts/run_unit_tests && php /tmp/run_unit_tests
